services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis_secure
    command: >
      redis-server 
      --bind "${REDIS_HOST}"
      --aclfile /usr/local/etc/redis/users.acl 
      --appendonly yes
      --loglevel notice
    ports:
      - "${REDIS_HOST}:${REDIS_PORT}:6379" # REDIS_HOST auf localhost setzen
    volumes:
      - redis-data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true # verhindert Rechte-Eskalation

volumes:
  redis-data:
    driver: local
