services:
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis_secure
    command: >
      redis-server 
      --requirepass "${REDIS_ADMIN_PASSWORD}" 
      --aclfile /usr/local/etc/redis/users.acl 
      --appendonly yes
      --loglevel notice
    ports:
      - "127.0.0.1:${REDIS_PORT}:6379"
    volumes:
      - redis-data:/data
      - ./users.acl:/usr/local/etc/redis/users.acl:ro
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - redis_net

volumes:
  redis-data:
    driver: local

networks:
  redis_net:
    driver: bridge